### ISSUE TITLE
Translation issue: All the text needs to be translation ready

### ISSUE THREAD

**Issue by codersantosh** [WordPress/twentytwentyfive#160]
**Description**
I've noticed a few strings that need translation on patterns and templates. Are these currently under review for finalization, and will the pattern designer push the final version? Also, how do you plan to translate the text within .html files?

**Comment by carolinan** [comment]
Translations will be finalized later before the 6.7 string freeze.
This is because there will be several changes to the templates and pattern files while the theme is developed.


The problems with adding the translations early is that
- the PHP code creates block validation error if it is not copied correctly
- the PHP is removed every time a change is made in the editor, so re-adding the translation functions over and over is a time-sink that should be avoided.


The theme does not add any extra functionality for translations. The text needs to be added in the PHP files.

**Comment by codersantosh** [comment]
Thank you, @carolinan, for answering all my questions. Best of luck to you and the team on the project.

**Comment by carolinan** [comment]
I think it is fine to keep this open as this will be a task later.

**Comment by carolinan** [comment]
### What is internationalization?
Internationalization is the process of developing your theme, so it can easily be translated into other languages. 

https://developer.wordpress.org/apis/internationalization/
https://developer.wordpress.org/apis/internationalization/internationalization-guidelines/

**Comment by carolinan** [comment]
Pattern titles and descriptions do not need to be wrapped in the PHP translation functions. This is handled elsewhere in WordPress:
```
/**
 * Title: Services - Three Columns
 * Description: Displays three columns with images and text for services.
 *
```

These type of texts need to be made translatable:
```
	<!-- wp:heading {"align":"wide"} -->
	<h2 class="wp-block-heading alignwide">Our services</h2>
	<!-- /wp:heading -->
```

`alt="Image for service"`

In this case, the placeholder should be removed because it is not used.  And because there are multiple of these no results blocks in the theme, they should all use identical translatable strings for the paragraph.
```
	<!-- wp:query-no-results -->
		<!-- wp:paragraph {"placeholder":"Add text or blocks that will display when a query returns no results."} -->
		<p>No posts were found.</p>
		<!-- /wp:paragraph -->
	<!-- /wp:query-no-results -->
```

In the search block, both the label, placeholder, and button text needs to be translation ready:

```<!-- wp:search {"label":"<?php esc_html_e( 'Search', 'twentytwentyfive' ); ?>","showLabel":false,"placeholder":"<?php echo esc_attr_x( 'Type something...', 'input placeholder text', 'twentytwentyfive' ); ?>","buttonText":"<?php echo esc_attr_x( 'Search', 'button label', 'twentytwentyfive' ); ?>","style":{"border":{"radius":"999px"}}} /-->```

**Comment by juanfra** [comment]
When it comes to translations, there's a good summary of which functions to use and for which cases in [the readme](https://github.com/WordPress/twentytwentyfive?tab=readme-ov-file#pattern-creation-guidelines), under "Different translation functions and when to use them".

**Comment by juanfra** [comment]
Just a heads up, since [this PR](https://github.com/WordPress/twentytwentyfive/pull/358) was merged, we have the `npm run lint:patterns:fix` command that will take care of having texts internationalized. 

We'll probably want to use context for some of them, but that command will be of great help for this task.
