### ISSUE TITLE
Uniform Way of Registering Block Style

### ISSUE THREAD

**Issue by codersantosh** [WordPress/twentytwentyfive#236]
**Description**
I noticed that all block styles are being registered through JSON. Is there a specific reason why the "Checkmark" style is being registered via PHP?

**Comment by carolinan** [comment]
Great question.
I can't think of any other reasons than:
- The CSS is more readable. In the JSON files, the custom CSS has to be on one single line.
- This style variation do not change any default block settings and styles such as typography or colors.

If this checkmark needs to look different in different style sections we might have to reconsider.
Otherwise there is no benefit to using a uniform way of registering block styles, its case by case.

**Comment by carolinan** [comment]
In my quick test, I did not find any issues with the checkmark across the variations. It does not define a color, so there are no contrast issues.
So I am closing this issue.
