### ISSUE TITLE
The paragraph block text overlapping.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfive#287]
**Description**
Hello Team,

I have reviewed the **"Paragraph Block"** and found that it's text is overlapping when we changes it's style from "Default" to "Pill" and change it font-size to larger size.

**Step-by-step reproduction instructions**

- Go to admin and select the "paragraph" block first.
- Add its paragraph text.
- Now, try to change it's block style from "Default" to "pill"
- Then change text font-size to larger size.
- Update the page and check its admin text and front-end text.

**Expected behavior**
I think that the text is displaying within border when we change its style to "Pill"

**Screenshots**
Here, I have provided it's issue video and screenshots for better reference:

**Issue video:**
-----------------

https://github.com/user-attachments/assets/73981e2f-fcce-48d5-92b6-0f77a7b7adfc

**Screenshots:**
------------------
**Editor:**
![paragraph-block-editor-side](https://github.com/user-attachments/assets/ceaab7ac-90b4-45d1-b232-8c92dc9753e2)

**Front-end**
![paragraph-block-front-end-side](https://github.com/user-attachments/assets/f969f98c-27cc-4405-a390-6978dbe84c04)

**Environment info**

- Device: Macbook M1
- OS: 14.6.1 (23G93)
- Browser: Google Chrome
- Version 128.0.6613.120 (Official Build) (arm64)
- WordPress version: 6.6.2 running, Gutenberg 19.2.0 , Theme active: Twenty Twenty-Five,

**Additional context**
I have tested this issue with active and inactive Gutenberg plugin and I am getting this issue.

Thanks,

**Comment by carolinan** [comment]
Hi @viralsampat-multidots 

Yes, this is a known limitation with some blocks and the border radius. This is not a bug with the theme.
When the border option was added to these blocks, it was a compromise;  it is better to have the option, and let users add padding, than to not have the option at all.

It also happens if a user adds a border to the paragraph without using the pill style, and with some other blocks.
