### ISSUE TITLE
theme.json missing customTemplates of templates folder.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfive#289]
**Description**
There are seven templates in the "templates" folder, but there are not registered in customTemplates within the theme.json file.

Thanks,

**Comment by carolinan** [comment]
This is correct, only one of them is a custom template, and that is page-no-title.
All other templates are part of the template hierarchy, and they are the default templates when users creates pages or posts and archive templates. They do not need to be listed in theme.json, because their names are already showing correctly in the template list in the Site Editor.
