### ISSUE TITLE
Using photos of people without model releases

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#360]
**Description**

@jasmussen Here is another question for the lawyers / legal team.
Since the theme is licensed as GPL and can be used for commercial use, is it acceptable to use photos of people with their faces showing,  when the photo is in the public domain, but there are no model releases?

The WordPress.org photo directory does not accept photos that show peoples faces, afaik for this reason, but it is not stated very clearly.
```
The photo must not contain faces of people.
For legal reasons, at this time submissions can’t contain the faces of people.
```

**Comment by jasmussen** [comment]
I'll double check with a legal friend! However I've quite the confidence myself that if an image is released into public domain, it means _no restrictions_, and the content of the photo is irrelevant, faces or not. But I'll report back when I have a clearer statement.

**Comment by juanfra** [comment]
My assumption is in line with Joen's. If an image is released into the public domain, specifically under the license we're using, I don't see why we should have a limitation.

**Comment by carolinan** [comment]
Google found me this:
https://wpandlegalstuff.com/a-reader-asks-theme-reviews-cc0-model-releases-and-gpl-compatibility/

I had forgotten about this. TLDR:

### Is a CC0’d image without a model release GPL compatible?
..if the image is of a person or copyright property (e.g., an artwork) for which no release has been obtained when one should have been obtained, then the answer is probably no. The answer is no because the absence of the relevant release either may or will mean that a component of the theme files (some or all of an images folder) cannot be used to the same extent that the other components can under the GPL.


...Placing this in the context of themes submitted to WordPress.org that contain CC0 images and considering now all potential sources of such images, one cannot discount the risk that, where the image files include photos of identifiable people (or property for which a property release may be required), there is a risk that not all required model (or property) releases have been obtained. If they haven’t been obtained, and sometimes depending on the nature of the photos and the circumstances in which they were taken, users of the themes may be at risk if they too publish the photos.

**Comment by jasmussen** [comment]
I heard back from a lawyer who noted that if it’s in public domain, to go ahead.

**Comment by carolinan** [comment]
I am very uncomfortable with risking users getting legal problems because they use the images for commercial use without the person's permission. Especially the woman who's personal information is in the sample content.

**Comment by carolinan** [comment]
>personal information is in the sample content.

Which I still think is a really bad idea, is it even in accordance with privacy laws? What if she or her relatives need to request the information to be removed after the theme is released?

**Comment by jasmussen** [comment]
The photos are a fundamental design principle as part of the theme concept of stories, without them, the design loses, very literally, character. I'll escalate this, see if I can get a response here on the thread, but in the mean time I would appeal to no rash removals of the photos, since they played such a critical role in finding this design in the first place.

**Comment by jasmussen** [comment]
Added note as I'm waiting to hear back, it is worth stating that the photos exist to support the patterns you use to build out the page. In other words, it's demo content. To that end, and to support your point, it would likely be a good idea to change the actual _text_ of the patterns that use these images, to refer to fictional people and events.

**Comment by jasmussen** [comment]
Apologies for the belated response, wanted to be sure all options were checked thoroughly. Although legally the images were still allowed (though with the caveat that we should make sure they were American citizens), some of the other concerns raised in this issue were echoed. To that end, and out of an abundance of caution, I share the concern raised by Carolina, regarding the ethics of using identifiable individuals in more recent photos. 

In an effort to minimize design changes and preserve the original spirit of the project, however, I did inquire about some of the older pictures as well, since they date back more than a century and are free from personal information. Specifically, these:
  
* [Vash Gon](https://www.rawpixel.com/image/14262822/vash-gon-jicarilla-edward-curtis), 1904, in the [Getty Museum collection](https://www.getty.edu/art/collection/object/1046J0).
* [New York [Portrait – Washington Square]](https://www.rawpixel.com/image/14264288/photograph-new-york-portrait-washington-square-paul-strand), 1916, [Getty Museum collection](https://www.getty.edu/art/collection/object/108HFF).
* [African Woman by Pascal Sébah and Jean Pascal Sébah](https://www.rawpixel.com/image/14263497/african-woman-pascal-sebah-and-jean-pascal-sebah), about 1878, [Getty Museum collection](https://www.getty.edu/art/collection/object/1049R1).

The response I got was that these historical pictures of adults from 108+ years ago are fine to use, because we can be confident the individuals in these photos are deceased, and there's little to no chance that someone alive today would automatically recognize one of these folks as their ancestor.

For that reason, I would like to advocate for retaining these specific images. They keep the spirit and character of the Stories theme, and add diversity and historical depth. Let me know your thoughts.

**Comment by juanfra** [comment]
Thank you Joen!
