### ISSUE TITLE
Sidebar flickers when selecting an archive template design

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#393]
**Description**

I don't know if this is because of the template blocks, the posts that are in the preview, the view port width, or a bug unrelated to the theme, but when I choose between the design for the archive template, the sidebar flickers. Please see the video.

Go to Appearance > Editor > Templates. Select "All archives"
Open the Template tab.
Open the Design panel.
Click on different designs. Save, and reset.

**Expected behavior**

No flickering.

**Screenshots**

https://github.com/user-attachments/assets/10c0614c-afa5-41c0-894b-0b623016950e

**Environment info**
Windows 11
Chrome version 129.0.6668.59
Resolution: 1920x1080
Gutenberg trunk/ development version

**Comment by kimclow** [comment]
Hey @carolinan 
I'm testing this on a local site:
 Macbook Pro 16-inch 2021. 
Chrome Version 128.0.6613.138

I am getting a very slight flicker. It's as if all the designs reload as soon as you select one. Have a look here: https://d.pr/v/hpa6xt 


https://github.com/user-attachments/assets/449e12ec-b4ab-409f-95df-1e86e12abb9e

**Comment by whatcodehaveyougit** [comment]
https://github.com/user-attachments/assets/e9020ba4-d1f2-4a1d-9c3d-38f59f67d956

Cannot seem to recreate the bug on WP Local interestingly.

Device: MacBook Retina, 13-inch, 2019
Running the up to date version of FireFox & Chrome version 129.0.6668.59 (Official Build) (x86_64)

**Comment by carolinan** [comment]
Thank you for testing.

I think it has something to do with the width or length of the pattern affecting the display of the scrollbar. It certainly is distracting.

**Comment by carolinan** [comment]
404 page template. Here I have only opened the panel, and I'm not hovering over the design or any buttons etc.
For some reason, the recording shows a slow flickering, but I am seeing it flicker much faster.

https://github.com/user-attachments/assets/ffd31e76-aa1f-4e17-8bbb-92fe682fcde8

**Comment by t-hamano** [comment]
This issue is probably only noticeable on Windows OS and Chrome because in Chrome on Windows OS, the browser scrollbars are not floating and take up the physical width.

I think this issue is not theme-specific, but a Gutenberg issue. The reason for the issue is as follows:

- Open the Design panel. The scrollbars are displayed because the content of the Design panel is vertically long.
- Select one of the patterns. The Design panel is then re-rendered. Immediately after the re-rendering starts, the scrollbars are not displayed because there is no content in the Design panel.
- The Design panel is re-rendered. The scrollbars are displayed because the content of the Design panel is vertically long.

This issue should be reproducible in WP 6.6 with the introduction of the Design panel.

Either way, it would be a good idea to submit an issue in the Gutenberg repository.

**Comment by kimclow** [comment]
> This issue should be reproducible in WP 6.6 with the introduction of the Design panel.

I'll test this.

**Comment by kimclow** [comment]
> with the introduction of the Design panel.

Oh actually is this a new feature with 6.7? I'll check 😅

**Comment by t-hamano** [comment]
@kimclowa8c 

The design panel should be available in WP 6.6. I confirmed the issue on the Playground: https://playground.wordpress.net/?php=8.0&wp=6.6


https://github.com/user-attachments/assets/726db1a5-e051-404c-912f-dea887f1f8cc

**Comment by carolinan** [comment]
I am going to close this because it has been reported in the Gutenberg GitHub repository. https://github.com/WordPress/gutenberg/issues/65847
