### ISSUE TITLE
Admin - Instagram Grid displays wider then other patterns in zoomed out page

### ISSUE THREAD

**Issue by severine-pozzo** [WordPress/twentytwentyfive#541]
**Description**
Instagram Grid makes the zoomed out admin page change width

**Step-by-step reproduction instructions**
1. Create a new Page
2. Add the Instagram grid pattern with other patterns
3. Zoom out
4. Then remove the Instagram grid pattern

**Expected behavior**
The zoomed out page displays in the consistent width, within the white background

**Screenshots**

**Environment info**
 - Device: Windows 11 Version 23H2
 - Browser: Chrome
 - Version: Version 129.0.6668.60

**Additional context**

Screencast https://somup.com/cZ6Qq5HYwu

**Comment by severine-pozzo** [comment]
![Image](https://github.com/user-attachments/assets/c242350f-52cc-48e5-a536-6e7ea919a8db)

**Comment by carolinan** [comment]
Hi
This problem is not limited to this pattern, and not limited to this theme.
This has already been reported in the Gutenberg GitHub repository, and is being monitored.
https://github.com/WordPress/gutenberg/issues/65974
https://github.com/WordPress/gutenberg/issues/65673
So I am closing this issue
