### ISSUE TITLE
Hover effect is missing in button block

### ISSUE THREAD

**Issue by sudip-md** [WordPress/twentytwentyfive#546]
**Description**
Hover effect is missing in button block

**Step-by-step reproduction instructions**
1. Create New page 
2. Add button block and add button text
3. Publish page
4. go to FE page and hover on Button

**Expected behavior**
Default hover effect should be work on button

**Screenshots**
Video - https://github.com/user-attachments/assets/b614ea8b-fca2-4d43-994f-996844b56b59

**Environment info**
- WordPress: 6.7-beta2-59195
- PHP: 8.1.23
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.23)
- Browser: Chrome 129.0.0.0 (macOS)
- Theme: Twenty Twenty-Five 1.0
- MU-Plugins:
  * Testing 10up's Ad Refresh Control Plugin

**Comment by carolinan** [comment]
Hi @sudip-md 

The hover is not visible because you have replaced the button colors.
The colors the user adds always replaces the defaults, and they have a higher CSS specificity, otherwise, the color options would not work.

Once or if controls for hover and other sates are available, the theme may or may not support them depending on what the requirements are. The feature is not a part of WordPress 6.7.

**Comment by sudip-md** [comment]
@carolinan Thanks for looking into it. Let me close this issue.
