### ISSUE TITLE
Color problems with the social icons in "Link in bio with profile, links and wide margins"

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#557]
**Description**
The social icons in the "Link in bio with profile"  pattern has too low color contrast ratio against the pattern's background color in two of the variations.

**Step-by-step reproduction instructions**
Insert the "Link in bio with profile, links and wide margins" pattern.
Go to Appearance > Editor > Styles and test the pattern colors with the different combined styles.

**Screenshots**
Sunrise:
![Image](https://github.com/user-attachments/assets/e5c5ebff-04e6-41c8-bbaf-a84993cf18a2)

Midnight:
![Image](https://github.com/user-attachments/assets/3ac4ba5d-0da7-428f-8264-284def186619)

**Comment by beafialho** [comment]
Is there a chance that the social icons can have the same color as the text in the pattern?

**Comment by karmatosed** [comment]
@beafialho and @carolinan I've been exploring this a bit today and there are a few issues here which I think we can make a decision on workarounds.

The piece that is the hitch is:

`<!-- wp:social-links {"iconColor":"contrast","iconColorValue":"#111111","className":"is-style-logos-only"} -->`

What we want is a default color and also to unify by having one color, over letting it be all colors of the social icons.

The issue specifically is contrast is in those styles not going to be fitting, base is in one - accent in another. The problem is a dependable color that works across all basically. Another approach might be to see if this calls on the theme.json itself. I'm unsure about that approach though as doing directly on the pattern is neater.

**Comment by carolinan** [comment]
I don't think icon color can be set in theme.json. It is not part of the schema.

**Comment by carolinan** [comment]
- Changing the text color of the core/social-links did not change the icon color.
- Changing the text color of the core/social-link did change the icon color.

So by setting the text color of the core/social-link in theme.json to "currentColor", the icons will have the same colors as the text,
this color is set on the section style and has already been tested to pass the color contrast 🎉

**Comment by carolinan** [comment]
Ah, this broke the color contrast when the "default" or "pill shaped" block options are used.

**Comment by carolinan** [comment]
Huh, using currentColor directly in the pattern does not seem to create any block validation errors or other problems.

```
				<!-- wp:social-links {"iconColor":"currentColor","iconColorValue":"currentColor","className":"is-style-logos-only"} -->
				<ul class="wp-block-social-links has-icon-color is-style-logos-only">
					<!-- wp:social-link {"url":"#","service":"x"} /-->

					<!-- wp:social-link {"url":"#","service":"instagram"} /-->

					<!-- wp:social-link {"url":"#","service":"whatsapp"} /-->
				</ul>
				<!-- /wp:social-links -->
```
