### ISSUE TITLE
Link underline thickness inconsistency across post terms and author

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#612]
If you notice, post author name has a thicker underline than categories. This is happening in all style variations.

![Image](https://github.com/user-attachments/assets/3ed9fefa-55f8-4ff3-a7a4-bdbd406de215)
![Image](https://github.com/user-attachments/assets/88806203-ee2a-4a8d-928c-d17b90faade7)
![Image](https://github.com/user-attachments/assets/4b610897-ba76-4a71-bd3e-bcbc00a30824)
![Image](https://github.com/user-attachments/assets/3f652dd4-2d19-4809-b8dc-fab7763a587c)

**Comment by carolinan** [comment]
In the editor, only the author name is an actual link.  It uses the custom CSS that the theme adds to all links:

```
a {
	text-decoration-thickness: 1px !important;
	text-underline-offset: .1em;
}
```

The post term is a `span`, so it does not use the link styles.

**Comment by beafialho** [comment]
Can we match the look of all the link underlines?

**Comment by carolinan** [comment]
I don't understand what you mean.
The category is only a link on the front. In the editor it is not a link underline.

**Comment by carolinan** [comment]
I think you may be suggesting that in the editor stylesheet, this CSS

```
/*
 * Link styles
 * https://github.com/WordPress/gutenberg/issues/42319
 */
a {
	text-decoration-thickness: 1px !important;
	text-underline-offset: .1em;
}
```

Should apply to all blocks that have the text decoration option set to underline.

**Comment by carolinan** [comment]
I did a very quick test.
When the text-decoration option is enabled on the block, there is no class name that we can target with CSS.

The only thing we have to identify that the option is enabled, is this inline style on the block:
`style="text-decoration: underline;"`

**Comment by juanfra** [comment]
Hi @beafialho - Thank you for opening this one. I can see this is noticeable in the editor's context. Here's a screencast of how I see it on `trunk`

https://github.com/user-attachments/assets/440b0cf2-12f9-47c4-b7d9-eb26b7cbde94

I also remember there was [an issue](https://github.com/WordPress/twentytwentyfive/issues/72) to customize the links so that they were "less rough". But now I'm a bit in doubt about what the expectation would be for links.

Can you please confirm what the expected behavior is when fixing this issue? We have two open PRs for this, [one](https://github.com/WordPress/twentytwentyfive/pull/615) that's fixing the display in the editor so that there's no difference between the post terms and author, and the [other approach](https://github.com/WordPress/twentytwentyfive/pull/616) where we are adjusting the links site-wide.


[Screencast of this PR](https://github.com/WordPress/twentytwentyfive/pull/615)

https://github.com/user-attachments/assets/e0ce27b5-ac7e-4d7f-b7f3-f70876370203

---

[Screencast of this PR](https://github.com/WordPress/twentytwentyfive/pull/616)

https://github.com/user-attachments/assets/933d411f-917c-4ccc-bf05-b8fdd40b9c51

**Comment by beafialho** [comment]
Thank you! I just tested both. It seems that links in #616 work as intended 👍

**Comment by carolinan** [comment]
The category is not a link in the Site Editor, with 616 the editor and front does not match.

**Comment by juanfra** [comment]
~I believe we can apply https://github.com/WordPress/twentytwentyfive/pull/615 on top of https://github.com/WordPress/twentytwentyfive/pull/616 then, as they both can coexist.~ Nevermind, I just checked and it's not possible.
