### ISSUE TITLE
Customize TT5's link styles

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#72]
Because the link styles usually look a bit rough, I suggest we add something like the following, unless someone has a better alternative, to improve the appearance of the theme's link underlines.

```
/*
 * Link styles
 * https://github.com/WordPress/gutenberg/issues/42319
 */
a {
	text-decoration-thickness: 1px !important;
	text-underline-offset: .1em;
}
```

Here's a before/after:
![Captura de ecrã 2024-08-19, às 11 35 51](https://github.com/user-attachments/assets/feb16c62-9ae2-4e4d-88d1-cc75c7286e2f)
![Captura de ecrã 2024-08-19, às 11 36 04](https://github.com/user-attachments/assets/3a918009-a8a7-413a-87ab-949d6225e379)

**Comment by beafialho** [comment]
cc: @carolinan @juanfra @richtabor

**Comment by carolinan** [comment]
I think we should add this to style.css (!) and not theme.json, for the same reasons mentioned in
https://github.com/WordPress/twentytwentyfive/issues/6

**Comment by beafialho** [comment]
Yes, my intent was to add it to `style.css`

**Comment by carolinan** [comment]
I wonder if there should also be an animation to ease it in and out?

**Comment by beafialho** [comment]
> I wonder if there should also be an animation to ease it in and out?

That would be so cool!

**Comment by melchoyce** [comment]
It's not currently possible to add an animation between `text-decoration: none` and `text-decoration: underline.` The only properties that can animate are `text-decoration-color` and `text-decoration-thickness.` I've tried a few iterations of animating `text-decoration-color` and don't think it'll work based on how the styles are set up. In order to add an animation, we'd need to refactor the underline styles to use pseudo-classes instead of `text-decoration` for link styles.

**Comment by carolinan** [comment]
Thank you @melchoyce. I will close this issue as completed. 😞
